name: frontend
description: "Quantum Secure Chat App"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  #https://pub.dev/packages/bloc
  bloc: ^9.0.0
  #https://pub.dev/packages/dio
  dio: ^5.8.0+1
  #https://pub.dev/packages/device_info_plus
  device_info_plus: ^11.5.0
  #https://pub.dev/packages/equatable
  equatable: ^2.0.7
  #https://pub.dev/packages/talker_flutter
  talker_flutter: ^5.0.0-dev.12
  #https://github.com/Frezyx/talker/tree/master/packages/talker_dio_logger
  talker_dio_logger: ^5.0.0-dev.12
  #https://github.com/Frezyx/talker/tree/master/packages/talker_bloc_logger
  talker_bloc_logger: ^5.0.0-dev.12
  flutter:
    sdk: flutter
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^9.1.1
  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.4
  #https://pub.dev/packages/flutter_svg

  flutter_svg: ^2.2.0
  #https://pub.dev/packages/get_it
  get_it: ^8.2.0
  #https://pub.dev/packages/go_router
  go_router: ^16.1.0
  #https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1
  #https://pub.dev/packages/intl
  intl: ^0.20.2
  #https://pub.dev/packages/crypto
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
